Repository kookmin-sw/capstone-2024-19, pull requests merged in 2024-04, with the labels that each got.

#62 [DOCS] PR-Template 변경
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📃 Docs, 🥇 urgency 1

#64 [DOCS] 중간발표전 메인브랜치 README 업데이트
  README.md
Labels: 📃 Docs, 🧹 Chore

#79 [DEPLOY] Redis-Cluster Helm을 이용하여 배포
  helm/redis-cluster/.helmignore
  helm/redis-cluster/Chart.lock
  helm/redis-cluster/Chart.yaml
  helm/redis-cluster/README.md
  helm/redis-cluster/charts/common/.helmignore
  helm/redis-cluster/charts/common/Chart.yaml
  helm/redis-cluster/charts/common/README.md
  helm/redis-cluster/charts/common/templates/_affinities.tpl
  helm/redis-cluster/charts/common/templates/_capabilities.tpl
  helm/redis-cluster/charts/common/templates/_compatibility.tpl
  helm/redis-cluster/charts/common/templates/_errors.tpl
  helm/redis-cluster/charts/common/templates/_images.tpl
  helm/redis-cluster/charts/common/templates/_ingress.tpl
  helm/redis-cluster/charts/common/templates/_labels.tpl
  helm/redis-cluster/charts/common/templates/_names.tpl
  helm/redis-cluster/charts/common/templates/_resources.tpl
  helm/redis-cluster/charts/common/templates/_secrets.tpl
  helm/redis-cluster/charts/common/templates/_storage.tpl
  helm/redis-cluster/charts/common/templates/_tplvalues.tpl
  helm/redis-cluster/charts/common/templates/_utils.tpl
  helm/redis-cluster/charts/common/templates/_warnings.tpl
  helm/redis-cluster/charts/common/templates/validations/_cassandra.tpl
  helm/redis-cluster/charts/common/templates/validations/_mariadb.tpl
  helm/redis-cluster/charts/common/templates/validations/_mongodb.tpl
  helm/redis-cluster/charts/common/templates/validations/_mysql.tpl
  helm/redis-cluster/charts/common/templates/validations/_postgresql.tpl
  helm/redis-cluster/charts/common/templates/validations/_redis.tpl
  helm/redis-cluster/charts/common/templates/validations/_validations.tpl
  helm/redis-cluster/charts/common/values.yaml
  helm/redis-cluster/templates/NOTES.txt
  helm/redis-cluster/templates/_helpers.tpl
  helm/redis-cluster/templates/configmap.yaml
  helm/redis-cluster/templates/extra-list.yaml
  helm/redis-cluster/templates/headless-svc.yaml
  helm/redis-cluster/templates/metrics-prometheus.yaml
  helm/redis-cluster/templates/metrics-svc.yaml
  helm/redis-cluster/templates/networkpolicy.yaml
  helm/redis-cluster/templates/poddisruptionbudget.yaml
  helm/redis-cluster/templates/prometheusrule.yaml
  helm/redis-cluster/templates/psp.yaml
  helm/redis-cluster/templates/redis-role.yaml
  helm/redis-cluster/templates/redis-rolebinding.yaml
  helm/redis-cluster/templates/redis-serviceaccount.yaml
  helm/redis-cluster/templates/redis-statefulset.yaml
  helm/redis-cluster/templates/redis-svc.yaml
  helm/redis-cluster/templates/scripts-configmap.yaml
  helm/redis-cluster/templates/secret.yaml
  helm/redis-cluster/templates/svc-cluster-external-access.yaml
  helm/redis-cluster/templates/tls-secret.yaml
  helm/redis-cluster/templates/update-cluster.yaml
  helm/redis-cluster/values.yaml
Labels: 🌏 Deploy, ✨ Feature

#90 [Feature] #89 컴포지트 서버 개발 및 카프카, 인가절차 개발.
  auth-service/src/main/java/com/jumunseo/authservice/domain/jwt/service/RefreshTokenServiceImpl.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/user/service/UserServiceImpl.java
  auth-service/src/main/java/com/jumunseo/authservice/global/exception/GlobalExceptionHandler.java
  auth-service/src/main/java/com/jumunseo/authservice/global/security/AuthenticationFilter.java
  auth-service/src/main/java/com/jumunseo/authservice/global/util/JwtTokenProvider.java
  composite-service/.gitignore
  composite-service/build.gradle
  composite-service/gradle/wrapper/gradle-wrapper.jar
  composite-service/gradle/wrapper/gradle-wrapper.properties
  composite-service/gradlew
  composite-service/gradlew.bat
  composite-service/settings.gradle
  composite-service/src/main/java/com/jumunseo/compositeservice/CompositeserviceApplication.java
  composite-service/src/main/java/com/jumunseo/compositeservice/command/controller/CommandController.java
  composite-service/src/main/java/com/jumunseo/compositeservice/command/dto/CommandDto.java
  composite-service/src/main/java/com/jumunseo/compositeservice/command/dto/external/DeleteChat.java
  composite-service/src/main/java/com/jumunseo/compositeservice/command/service/KafkaService.java
  composite-service/src/main/java/com/jumunseo/compositeservice/global/config/CorsConfig.java
  composite-service/src/main/java/com/jumunseo/compositeservice/global/config/KafkaConfig.java
  composite-service/src/main/java/com/jumunseo/compositeservice/global/config/SecurityConfig.java
  composite-service/src/main/java/com/jumunseo/compositeservice/global/exception/Code.java
  composite-service/src/main/java/com/jumunseo/compositeservice/global/exception/CustomErrorController.java
  composite-service/src/main/java/com/jumunseo/compositeservice/global/exception/CustomException.java
  composite-service/src/main/java/com/jumunseo/compositeservice/global/exception/GlobalExceptionHandler.java
  composite-service/src/main/java/com/jumunseo/compositeservice/global/exception/Result.java
  composite-service/src/main/java/com/jumunseo/compositeservice/global/security/AuthorizationFilter.java
  composite-service/src/main/java/com/jumunseo/compositeservice/global/security/JwtProvider.java
  composite-service/src/main/java/com/jumunseo/compositeservice/query/controller/QueryController.java
  composite-service/src/main/resources/application-deploy.yml
  composite-service/src/main/resources/application.yml
  composite-service/src/test/java/com/jumunseo/compositeservice/CompositeserviceApplicationTests.java
  composite-service/src/test/java/com/jumunseo/compositeservice/kafka_test/TestKafkaConfig.java
  composite-service/src/test/java/com/jumunseo/compositeservice/kafka_test/TestListener.java
Labels: ✨ Feature, ✅ Test, 🔨 Refactor

#97 [FEATURE] #88 MSA 의 CUD,R 의 분리를 위한 Kafka(CUD) 적용과 WebFlux(R) 적용
  composite-service/build.gradle
  composite-service/src/main/java/com/jumunseo/compositeservice/command/controller/MagicianCommandController.java
  composite-service/src/main/java/com/jumunseo/compositeservice/command/controller/TestCommandController.java
  composite-service/src/main/java/com/jumunseo/compositeservice/query/config/WebClientConfig.java
  composite-service/src/main/java/com/jumunseo/compositeservice/query/controller/MagicianQueryController.java
  composite-service/src/main/java/com/jumunseo/compositeservice/query/controller/QueryController.java
  composite-service/src/test/java/com/jumunseo/compositeservice/kafka_test/TestListener.java
  magician/magician-env-docker-compose.yml
  magician/main.py
  magician/requirements.txt
  magician/test_magician.py
Labels: ✨ Feature, 🐞 BugFix, 🔨 Refactor, 🥇 urgency 1

#98 [Feature] #91 -GitHub Action을 이용한 CI/CD 구현 for Composite-Server
  .github/workflows/auth-server-deploy.yml
  .github/workflows/composite-service-test.yml
  .github/workflows/deploy.yml
  .github/workflows/magician-deploy.yml
  composite-service/.gitignore
  composite-service/Dockerfile
  composite-service/README.md
  composite-service/composite-env-docker-compose.yml
  composite-service/src/main/resources/application-deploy.yml
  composite-service/src/main/resources/application-test.yml
  composite-service/src/test/java/com/jumunseo/compositeservice/CompositeserviceApplicationTests.java
  composite-service/src/test/java/com/jumunseo/compositeservice/kafka_test/TestKafkaConfig.java
  composite-service/src/test/java/com/jumunseo/compositeservice/kafka_test/TestListener.java
  magician/magician-env-docker-compose.yml
  magician/main.py
Labels: ⚙ Setting, 💻 CrossBrowsing, 🌏 Deploy, ✨ Feature, ✅ Test

#107 로그인 틀 마련 #106
  jumunseo/lib/config/routes/app_routes.dart
  jumunseo/lib/core/login_status.dart
  jumunseo/lib/features/community/community_screen.dart
  jumunseo/lib/features/dilemma/dilemma_screen.dart
  jumunseo/lib/features/home/cubit/home_cubit.dart
  jumunseo/lib/features/home/state/home_state.dart
  jumunseo/lib/features/home/view/home_screen.dart
  jumunseo/lib/features/login/cubit/login_cubit.dart
  jumunseo/lib/features/login/cubit/login_state.dart
  jumunseo/lib/features/login/login.dart
  jumunseo/lib/features/login/view/login_ask_dialog.dart
  jumunseo/lib/features/login/view/login_screen.dart
  jumunseo/lib/shared/blocs.dart
  jumunseo/pubspec.lock
  jumunseo/pubspec.yaml
Labels: ✨ Feature

#111 Front/feature/community 커뮤니티 틀 마련
  jumunseo/lib/config/routes/app_routes.dart
  jumunseo/lib/features/community/community.dart
  jumunseo/lib/features/community/community_screen.dart
  jumunseo/lib/features/community/detail/community_detail.dart
  jumunseo/lib/features/community/detail/cubit/community_detail_cubit.dart
  jumunseo/lib/features/community/detail/cubit/community_detail_state.dart
  jumunseo/lib/features/community/detail/model/community_detail_model.dart
  jumunseo/lib/features/community/detail/model/community_detail_model.freezed.dart
  jumunseo/lib/features/community/detail/model/community_detail_model.g.dart
  jumunseo/lib/features/community/detail/view/community_detail_screen.dart
  jumunseo/lib/features/community/home/community_home.dart
  jumunseo/lib/features/community/home/cubit/community_home_cubit.dart
  jumunseo/lib/features/community/home/cubit/community_home_state.dart
  jumunseo/lib/features/community/home/view/community_home_screen.dart
  jumunseo/lib/features/community/postedit/community_postedit.dart
  jumunseo/lib/features/community/writing_status.dart
  jumunseo/lib/features/home/view/community_menu.dart
  jumunseo/lib/features/wizard/model/chat_model.freezed.dart
  jumunseo/lib/features/wizard/model/room_model.freezed.dart
  jumunseo/lib/features/wizard/model/room_model.g.dart
  jumunseo/lib/shared/svg_strings.dart
  jumunseo/lib/shared/time_diff_string.dart
  jumunseo/pubspec.lock
  jumunseo/pubspec.yaml
Labels: ✨ Feature

#115 feat : 대댓글 틀 마련, 글쓰기 틀마련, 글 수정하기/글쓰기 동일 위젯 사용
  .DS_Store
  helm/.DS_Store
  jumunseo/lib/config/routes/app_routes.dart
  jumunseo/lib/features/community/community.dart
  jumunseo/lib/features/community/detail/view/community_detail_comment_widget.dart
  jumunseo/lib/features/community/detail/view/community_detail_reply_widget.dart
  jumunseo/lib/features/community/detail/view/community_detail_screen.dart
  jumunseo/lib/features/community/home/view/community_home_screen.dart
  jumunseo/lib/features/community/post/community_post.dart
  jumunseo/lib/features/community/post/cubit/community_post_cubit.dart
  jumunseo/lib/features/community/post/cubit/community_post_state.dart
  jumunseo/lib/features/community/post/model/community_post_model.dart
  jumunseo/lib/features/community/post/view/community_post_frame.dart
  jumunseo/pubspec.lock
Labels: ✨ Feature
