Repository kookmin-sw/capstone-2024-19, pull requests merged in 2024-03, with the labels that each got.

#7 [FEATURE] #4 - 마법사 기능 구현
  magician/.gitignore
  magician/gpt.py
  magician/main.py
  magician/requirements.txt
Labels: ⚙ Setting, ✨ Feature

#8 [FEATURE] #5 - 마법사 테스트 구현
  magician/test_magician.py
Labels: ✅ Test

#25 [Chore] #19 - helm 폴더 구성
  helm/README.md
Labels: ⚙ Setting, 📃 Docs, 🧹 Chore

#28 [FEATURE] #9 - 인증서버 기능 구현
  auth-service/.gitignore
  auth-service/build.gradle
  auth-service/gradle/wrapper/gradle-wrapper.jar
  auth-service/gradle/wrapper/gradle-wrapper.properties
  auth-service/gradlew
  auth-service/gradlew.bat
  auth-service/settings.gradle
  auth-service/src/main/java/com/jumunseo/authservice/AuthServiceApplication.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/jwt/controller/JwtController.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/jwt/dto/JwtTokenDto.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/jwt/exception/AccessTokenNotValidException.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/jwt/exception/RefreshTokenNotValidException.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/jwt/redis/RefreshToken.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/jwt/redis/RefreshTokenRedisRepository.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/jwt/service/AccessTokenService.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/jwt/service/AccessTokenServiceImpl.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/jwt/service/RefreshTokenService.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/jwt/service/RefreshTokenServiceImpl.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/user/controller/UserController.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/user/dto/Mapper.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/user/dto/SignupDto.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/user/dto/UserDto.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/user/entity/Role.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/user/entity/User.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/user/exception/NotExistUserException.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/user/repository/UserRepository.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/user/service/UserService.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/user/service/UserServiceImpl.java
  auth-service/src/main/java/com/jumunseo/authservice/global/config/AppConfig.java
  auth-service/src/main/java/com/jumunseo/authservice/global/config/CorsConfig.java
  auth-service/src/main/java/com/jumunseo/authservice/global/config/RedisConfig.java
  auth-service/src/main/java/com/jumunseo/authservice/global/config/SecurityConfig.java
  auth-service/src/main/java/com/jumunseo/authservice/global/dto/Code.java
  auth-service/src/main/java/com/jumunseo/authservice/global/dto/LoginRequest.java
  auth-service/src/main/java/com/jumunseo/authservice/global/dto/Result.java
  auth-service/src/main/java/com/jumunseo/authservice/global/exception/CustomException.java
  auth-service/src/main/java/com/jumunseo/authservice/global/security/AuthenticationFilter.java
  auth-service/src/main/java/com/jumunseo/authservice/global/security/AuthorizationFilter.java
  auth-service/src/main/java/com/jumunseo/authservice/global/util/CookieProvider.java
  auth-service/src/main/java/com/jumunseo/authservice/global/util/JwtTokenProvider.java
  auth-service/src/test/java/com/jumunseo/authservice/AuthServiceApplicationTests.java
Labels: ✨ Feature

#35 [DEPLOY] 쿠버네티스 클러스터에 kiali 배포
  helm/kiali-operator/Chart.yaml
  helm/kiali-operator/crds/crds.yaml
  helm/kiali-operator/templates/NOTES.txt
  helm/kiali-operator/templates/_helpers.tpl
  helm/kiali-operator/templates/clusterrole.yaml
  helm/kiali-operator/templates/clusterrolebinding.yaml
  helm/kiali-operator/templates/deployment.yaml
  helm/kiali-operator/templates/kiali-cr.yaml
  helm/kiali-operator/templates/ossmconsole-crd.yaml
  helm/kiali-operator/templates/serviceaccount.yaml
  helm/kiali-operator/values.yaml
Labels: ⚙ Setting, 🌏 Deploy

#32 [DEPLOY] 쿠버네티스 클러스터에 MetalLB 배포 및 설정
  helm/kubernetes-resource/metallb/ip-pool.yaml
  helm/kubernetes-resource/metallb/l2-advertisement.yaml
  helm/metallb/.helmignore
  helm/metallb/Chart.lock
  helm/metallb/Chart.yaml
  helm/metallb/README.md
  helm/metallb/charts/crds/.helmignore
  helm/metallb/charts/crds/Chart.yaml
  helm/metallb/charts/crds/README.md
  helm/metallb/charts/crds/templates/crds.yaml
  helm/metallb/charts/frr-k8s/.helmignore
  helm/metallb/charts/frr-k8s/Chart.lock
  helm/metallb/charts/frr-k8s/Chart.yaml
  helm/metallb/charts/frr-k8s/README.md
  helm/metallb/charts/frr-k8s/charts/crds/.helmignore
  helm/metallb/charts/frr-k8s/charts/crds/Chart.yaml
  helm/metallb/charts/frr-k8s/charts/crds/README.md
  helm/metallb/charts/frr-k8s/charts/crds/templates/frrk8s.metallb.io_frrconfigurations.yaml
  helm/metallb/charts/frr-k8s/charts/crds/templates/frrk8s.metallb.io_frrnodestates.yaml
  helm/metallb/charts/frr-k8s/templates/NOTES.txt
  helm/metallb/charts/frr-k8s/templates/_helpers.tpl
  helm/metallb/charts/frr-k8s/templates/controller.yaml
  helm/metallb/charts/frr-k8s/templates/rbac.yaml
  helm/metallb/charts/frr-k8s/templates/service-accounts.yaml
  helm/metallb/charts/frr-k8s/templates/service-monitor.yaml
  helm/metallb/charts/frr-k8s/templates/webhooks.yaml
  helm/metallb/charts/frr-k8s/values.schema.json
  helm/metallb/charts/frr-k8s/values.yaml
  helm/metallb/policy/controller.rego
  helm/metallb/policy/rbac.rego
  helm/metallb/policy/speaker.rego
  helm/metallb/templates/NOTES.txt
  helm/metallb/templates/_helpers.tpl
  helm/metallb/templates/controller.yaml
  helm/metallb/templates/deprecated_configInline.yaml
  helm/metallb/templates/exclude-l2-config.yaml
  helm/metallb/templates/podmonitor.yaml
  helm/metallb/templates/prometheusrules.yaml
  helm/metallb/templates/rbac.yaml
  helm/metallb/templates/service-accounts.yaml
  helm/metallb/templates/servicemonitor.yaml
  helm/metallb/templates/speaker.yaml
  helm/metallb/templates/webhooks.yaml
  helm/metallb/values.schema.json
  helm/metallb/values.yaml
Labels: ⚙ Setting, 🌏 Deploy

#36 [Deploy] #6 - 마법사 로컬 테스트를 위한 Docker 환경 구성 및 README 작성
  magician/.gitignore
  magician/Dockerfile
  magician/README.md
  magician/magician-env-docker-compose.yml
  magician/main.py
Labels: ⚙ Setting, 💻 CrossBrowsing, 🌏 Deploy, ✅ Test, 📃 Docs

#37 [DEPLOY] #15 인증서버 로컬 테스트를 위한 Docker 환경 구성 및 README 작성
  auth-service/.gitignore
  auth-service/Dockerfile
  auth-service/README.md
  auth-service/auth-service-env-docker-compose.yml
  auth-service/src/main/resources/application-test.yml
  auth-service/src/main/resources/application.yml
Labels: ⚙ Setting, 💻 CrossBrowsing, 🌏 Deploy, ✅ Test, 📃 Docs

#48 [FEATURE] #14 - 인증서버 테스트 구현
  auth-service/.gitignore
  auth-service/src/main/java/com/jumunseo/authservice/domain/user/controller/UserController.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/user/service/UserService.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/user/service/UserServiceImpl.java
  auth-service/src/main/resources/application-test.yml
  auth-service/src/main/resources/application.yml
  auth-service/src/test/java/com/jumunseo/authservice/config/TestConfig.java
  auth-service/src/test/java/com/jumunseo/authservice/controller/jwt/JwtControllerTest.java
  auth-service/src/test/java/com/jumunseo/authservice/controller/user/UserControllerTest.java
Labels: ✅ Test

#49 [REFACTOR] #46 - 인증서버 user update 시에 refresh 토큰 변경 및 access 토큰 변경 로직 추가, 테스트 추가
  auth-service/src/main/java/com/jumunseo/authservice/domain/jwt/controller/JwtController.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/jwt/redis/RefreshToken.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/user/controller/UserController.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/user/dto/UpdateDto.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/user/service/UserService.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/user/service/UserServiceImpl.java
  auth-service/src/main/java/com/jumunseo/authservice/global/util/JwtTokenProvider.java
  auth-service/src/test/java/com/jumunseo/authservice/controller/user/UserControllerTest.java
Labels: 🐞 BugFix, 🔨 Refactor, 🥇 urgency 1

#50 [FEATURE] #47 - 이메일 중복 예외 추가 및 중복 이메일 확인 API Endpoint 추가
  auth-service/src/main/java/com/jumunseo/authservice/domain/user/controller/UserController.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/user/exception/DuplicateEmailException.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/user/service/UserService.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/user/service/UserServiceImpl.java
  auth-service/src/test/java/com/jumunseo/authservice/controller/user/UserControllerTest.java
Labels: ✨ Feature, 🐞 BugFix, ✅ Test, 🔨 Refactor, 🥇 urgency 1

#54 [FIX] 프런트 서버 통신 방법 http에서 retrofit/dio로
  jumunseo/pubspec.lock
  jumunseo/pubspec.yaml
Labels: ✨ Feature, 🔨 Refactor, 📬 API

#56 [FEATURE] #43 - Github Action 을 통한 CI/CD 구현
  .github/workflows/auth-server-deploy.yml
  .github/workflows/auth-service-test.yml
  .github/workflows/magician-deploy.yml
  .github/workflows/magician-test.yml
  auth-service/.gitignore
  auth-service/Dockerfile
  auth-service/src/main/resources/application-deploy.yml
  auth-service/src/main/resources/application-test.yml
  auth-service/src/test/java/com/jumunseo/authservice/AuthServiceApplicationTests.java
  magician/magician-env-docker-compose.yml
  magician/main.py
  magician/requirements.txt
  magician/test_magician.py
Labels: 💻 CrossBrowsing, 🌏 Deploy, ✨ Feature, ✅ Test, 📃 Docs

#59 [FEATURE] 마법사 서버 연결 & 전체적인 기능 완성
  jumunseo/lib/features/wizard/chat/cubit/wizard_cubit.dart
  jumunseo/lib/features/wizard/chat/parsing/chat_parser.dart
  jumunseo/lib/features/wizard/chat/parsing/conversation_parser.dart
  jumunseo/lib/features/wizard/chat/parsing/room_parser.dart
  jumunseo/lib/features/wizard/chat/state/wizard_state.dart
  jumunseo/lib/features/wizard/chat/view/category_select.dart
  jumunseo/lib/features/wizard/chat/view/category_view.dart
  jumunseo/lib/features/wizard/chat/view/chat_view.dart
  jumunseo/lib/features/wizard/chat/view/fwohView/how_view.dart
  jumunseo/lib/features/wizard/chat/view/fwohView/plus_info_view.dart
  jumunseo/lib/features/wizard/chat/view/fwohView/what_view.dart
  jumunseo/lib/features/wizard/chat/view/fwohView/when_view.dart
  jumunseo/lib/features/wizard/chat/view/fwohView/where_view.dart
  jumunseo/lib/features/wizard/chat/view/fwohView/who_view.dart
  jumunseo/lib/features/wizard/chat/view/fwohView/why_view.dart
  jumunseo/lib/features/wizard/chat/view/fwoh_view.dart
  jumunseo/lib/features/wizard/chat/view/room_list_select.dart
  jumunseo/lib/features/wizard/chat/view/room_list_view.dart
  jumunseo/lib/features/wizard/chat/view/wizard_setting_select.dart
  jumunseo/lib/features/wizard/chat/view/wizard_setting_view.dart
  jumunseo/lib/features/wizard/data/repository/wizard_repository.dart
  jumunseo/lib/features/wizard/data/repository/wizard_repository.g.dart
  jumunseo/lib/features/wizard/model/chat_model.dart
  jumunseo/lib/features/wizard/model/chat_model.freezed.dart
  jumunseo/lib/features/wizard/model/chat_model.g.dart
  jumunseo/lib/features/wizard/model/conversation_model.dart
  jumunseo/lib/features/wizard/model/conversation_model.freezed.dart
  jumunseo/lib/features/wizard/model/conversation_model.g.dart
  jumunseo/lib/features/wizard/model/room_model.dart
  jumunseo/lib/features/wizard/model/room_model.freezed.dart
  jumunseo/lib/features/wizard/model/room_model.g.dart
  jumunseo/lib/shared/room_information.dart
  jumunseo/pubspec.lock
  jumunseo/pubspec.yaml
Labels: ✨ Feature

#61 [FEATURE] #57 마법사 대화삭제 기능 추가 + CORS 전체오픈
  magician/main.py
  magician/test_magician.py
Labels: 🐞 BugFix, ✅ Test, 🔨 Refactor, 🥇 urgency 1
