Repository kookmin-sw/capstone-2024-19, pull requests merged in 2024-05, with the labels that each got.

#118 [Feature] 인증서버 Swagger 추가
  auth-service/build.gradle
  auth-service/src/main/java/com/jumunseo/authservice/domain/jwt/controller/JwtController.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/user/controller/UserController.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/user/service/UserServiceImpl.java
  auth-service/src/main/java/com/jumunseo/authservice/global/config/SwaggerConfig.java
  auth-service/src/main/resources/application.yml
Labels: 📃 Docs, 📬 API

#122 [Feat] 프로필 이미지, 소셜로그인 , 차단기능 등등 간단한 수정 완료
  .github/workflows/auth-service-test.yml
  .github/workflows/deploy.yml
  auth-service/build.gradle
  auth-service/src/main/java/com/jumunseo/authservice/domain/user/controller/UserController.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/user/dto/Mapper.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/user/dto/OAuthAttributeDto.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/user/dto/UserDto.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/user/entity/BlockUser.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/user/entity/LoginType.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/user/entity/User.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/user/repository/BlockUserRepository.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/user/service/UserService.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/user/service/UserServiceImpl.java
  auth-service/src/main/java/com/jumunseo/authservice/global/config/SecurityConfig.java
  auth-service/src/main/java/com/jumunseo/authservice/global/exception/CredInfoNonCorrectException.java
  auth-service/src/main/java/com/jumunseo/authservice/global/exception/LocalIOException.java
  auth-service/src/main/java/com/jumunseo/authservice/global/exception/S3IOException.java
  auth-service/src/main/java/com/jumunseo/authservice/global/exception/SimpleIOException.java
  auth-service/src/main/java/com/jumunseo/authservice/global/photo/AwsConfig.java
  auth-service/src/main/java/com/jumunseo/authservice/global/photo/S3Uploader.java
  auth-service/src/main/java/com/jumunseo/authservice/global/security/AuthenticationFilter.java
  auth-service/src/main/java/com/jumunseo/authservice/global/security/ExceptionHandlerFilter.java
  auth-service/src/main/java/com/jumunseo/authservice/global/util/Oauth2Service.java
  auth-service/src/main/resources/application-deploy.yml
  auth-service/src/main/resources/application-test.yml
  debate/src/test/java/com/jumunseo/debate/DebateApplicationTests.java
  integration-docker-compose.yml
  magician/main.py
Labels: ⚙ Setting, 🌏 Deploy, ✨ Feature, 🐞 BugFix, ✅ Test, 🔨 Refactor, 📬 API

#124 [Fix] 멀티아크 이미지를 위한 깃허브액션 수정
  .github/workflows/deploy.yml
  auth-service/src/main/java/com/jumunseo/authservice/domain/user/controller/UserController.java
  auth-service/src/main/java/com/jumunseo/authservice/domain/user/service/UserServiceImpl.java
Labels: 🌏 Deploy, 🐞 BugFix, 📃 Docs, 🔨 Refactor

#125 [Fix] 타임존 에러 해결
  .github/workflows/deploy.yml
  auth-service/src/main/java/com/jumunseo/authservice/AuthServiceApplication.java
  auth-service/src/main/java/com/jumunseo/authservice/global/util/JwtTokenProvider.java
  composite-service/src/main/java/com/jumunseo/compositeservice/CompositeserviceApplication.java
  composite-service/src/main/java/com/jumunseo/compositeservice/query/controller/AuthQueryController.java
  composite-service/src/main/java/com/jumunseo/compositeservice/query/controller/DebateQueryController.java
  composite-service/src/main/java/com/jumunseo/compositeservice/query/controller/MagicianQueryController.java
  composite-service/src/main/resources/application-deploy.yml
  composite-service/src/main/resources/application-test.yml
  debate/build.gradle
  debate/src/main/java/com/jumunseo/debate/domain/opinion/controller/OpinionCommandController.java
  debate/src/main/java/com/jumunseo/debate/domain/opinion/dto/OpinionDto.java
  debate/src/main/java/com/jumunseo/debate/domain/opinion/dto/OpinionResponseDto.java
  debate/src/main/java/com/jumunseo/debate/domain/opinion/entity/Opinion.java
  debate/src/main/java/com/jumunseo/debate/domain/opinion/repository/OpinionJPARepository.java
  debate/src/main/java/com/jumunseo/debate/domain/subject/dto/SubjectDto.java
  debate/src/main/java/com/jumunseo/debate/domain/subject/entity/Subject.java
  debate/src/main/java/com/jumunseo/debate/domain/subject/service/SubjectServiceImpl.java
  debate/src/main/java/com/jumunseo/debate/global/TestController.java
  debate/src/main/java/com/jumunseo/debate/global/config/ObjectMapperConfig.java
  debate/src/main/java/com/jumunseo/debate/global/dto/Mapper.java
  debate/src/main/java/com/jumunseo/debate/global/stomp/RedisConfig.java
  integration-docker-compose.yml
Labels: 💻 CrossBrowsing, 🌏 Deploy, 🐞 BugFix

#126 [Feature] 커뮤니티 서버 1차 병합
  community/.gitignore
  community/build.gradle
  community/gradle/wrapper/gradle-wrapper.jar
  community/gradle/wrapper/gradle-wrapper.properties
  community/gradlew
  community/gradlew.bat
  community/settings.gradle
  community/src/main/java/com/jumunseo/community/CommunityApplication.java
  community/src/main/java/com/jumunseo/community/domain/post/controller/PostController.java
  community/src/main/java/com/jumunseo/community/domain/post/dto/CategoryDto.java
  community/src/main/java/com/jumunseo/community/domain/post/dto/CommentDto.java
  community/src/main/java/com/jumunseo/community/domain/post/dto/ImageDto.java
  community/src/main/java/com/jumunseo/community/domain/post/dto/PostDto.java
  community/src/main/java/com/jumunseo/community/domain/post/dto/RecommendationDto.java
  community/src/main/java/com/jumunseo/community/domain/post/dto/UserDto.java
  community/src/main/java/com/jumunseo/community/domain/post/entity/Category.java
  community/src/main/java/com/jumunseo/community/domain/post/entity/CategoryType.java
  community/src/main/java/com/jumunseo/community/domain/post/entity/Comment.java
  community/src/main/java/com/jumunseo/community/domain/post/entity/Image.java
  community/src/main/java/com/jumunseo/community/domain/post/entity/Post.java
  community/src/main/java/com/jumunseo/community/domain/post/entity/Recommendation.java
  community/src/main/java/com/jumunseo/community/domain/post/entity/RecommendationType.java
  community/src/main/java/com/jumunseo/community/domain/post/repository/CommentRepository.java
  community/src/main/java/com/jumunseo/community/domain/post/repository/ImageRepository.java
  community/src/main/java/com/jumunseo/community/domain/post/repository/PostRepository.java
  community/src/main/java/com/jumunseo/community/domain/post/repository/RecommendationRepository.java
  community/src/main/java/com/jumunseo/community/domain/post/service/PostService.java
  community/src/main/java/com/jumunseo/community/domain/post/service/PostServiceImpl.java
  community/src/main/java/com/jumunseo/community/global/config/PostgreSQLConfig.java
  community/src/main/java/com/jumunseo/community/global/dto/Code.java
  community/src/main/java/com/jumunseo/community/global/dto/Result.java
  community/src/main/java/com/jumunseo/community/global/exception/CustomException.java
  community/src/main/java/com/jumunseo/community/global/exception/GlobalExceptionHandler.java
  community/src/main/java/com/jumunseo/community/global/util/FileUtil.java
  community/src/main/resources/application.yml
  community/src/test/java/com/jumunseo/community/CommunityApplicationTests.java
Labels: ✨ Feature

#127 [Feature] 마법사 파인튜닝 모델 추가 및 데이터 편집
  magician/.gitignore
  magician/finetune/01.민사_edit/2017.jsonl
  magician/finetune/01.민사_edit/2018.jsonl
  magician/finetune/01.민사_edit/2019.jsonl
  magician/finetune/01.민사_edit/2020.jsonl
  magician/finetune/01.민사_edit/2021.jsonl
  magician/finetune/02.형사_edit/2017.jsonl
  magician/finetune/02.형사_edit/2018.jsonl
  magician/finetune/02.형사_edit/2019.jsonl
  magician/finetune/02.형사_edit/2020.jsonl
  magician/finetune/02.형사_edit/2021.jsonl
  magician/finetune/03.행정_edit/2017.jsonl
  magician/finetune/03.행정_edit/2018.jsonl
  magician/finetune/03.행정_edit/2019.jsonl
  magician/finetune/03.행정_edit/2020.jsonl
  magician/finetune/03.행정_edit/2021.jsonl
  magician/finetune/data_processor.py
  magician/finetune/fine_tuner.py
  magician/gpt.py
  magician/main.py
Labels: ✨ Feature, 📃 Docs

#129 [FIX] 소켓 주소 변경
  debate/src/main/java/com/jumunseo/debate/global/stomp/WebSocketConfig.java
  magician/main.py
  magician/test_magician.py
Labels: 💻 CrossBrowsing, 🐞 BugFix, 🔨 Refactor

#136 [Feature] 프론트 리이슈 추가
  jumunseo/lib/features/auth/cubit/auth_cubit.dart
  jumunseo/lib/features/auth/data/repository/auth_repository.dart
  jumunseo/lib/features/auth/data/repository/auth_repository.g.dart
  jumunseo/lib/features/auth/model/user_edit_response_model.dart
  jumunseo/lib/features/auth/model/user_edit_response_model.freezed.dart
  jumunseo/lib/features/auth/model/user_edit_response_model.g.dart
  jumunseo/lib/features/auth/model/user_info_response_model.dart
  jumunseo/lib/features/auth/model/user_info_response_model.freezed.dart
  jumunseo/lib/features/auth/model/user_info_response_model.g.dart
  jumunseo/lib/features/profile/view/profile_screen.dart
  jumunseo/lib/features/wizard/chat/cubit/wizard_cubit.dart
  jumunseo/lib/features/wizard/chat/view/room_list_view.dart
  jumunseo/lib/features/wizard/data/repository/wizard_repository.dart
  jumunseo/lib/features/wizard/data/repository/wizard_repository.g.dart
  jumunseo/lib/features/wizard/model/chat_model.dart
  jumunseo/lib/features/wizard/model/chat_model.freezed.dart
  jumunseo/lib/features/wizard/model/chat_model.g.dart
Labels: ✨ Feature, 🐞 BugFix, 🔨 Refactor

#140 [Docs] 리드미 업데이트
  README.md
Labels: 📃 Docs, 🧹 Chore

#144 [FIX] 익명으로 게시글 디테일 접근 가능, 좋아요 확인 로직의 분리
  community/src/main/java/com/jumunseo/community/domain/board/controller/BoardQueryController.java
  community/src/main/java/com/jumunseo/community/domain/board/service/BoardService.java
  community/src/main/java/com/jumunseo/community/domain/board/service/BoardServiceImpl.java
  composite-service/src/main/java/com/jumunseo/compositeservice/command/controller/CommunityCommandController.java
  composite-service/src/main/java/com/jumunseo/compositeservice/query/controller/CommunityQueryController.java
  debate/src/main/java/com/jumunseo/debate/domain/subject/repository/SubjectJPARepository.java
  debate/src/main/java/com/jumunseo/debate/domain/subject/service/SubjectService.java
  debate/src/main/java/com/jumunseo/debate/domain/subject/service/SubjectServiceImpl.java
  debate/src/main/java/com/jumunseo/debate/global/TestController.java
Labels: ✨ Feature, 🐞 BugFix, 🔨 Refactor, 📬 API
